server:
 port: 8085
 


spring:
  application:
   name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8084
              predicates:
                - Path=/users/**


            - id: booking-service
              uri: http://localhost:8082
              predicates:
                - Path=/booking/**


            - id: ambulence-service
              uri: http://localhost:8081
              predicates:
                - Path=/driver/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    gateway:
      access: READ_ONLY

    management:
     health:
       circuitbreakers:  
        enabled: true
       endpoints:
          web:
           exposure:
             include: health
       endpoint:
          health:
            show-details:  always			