server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ambulance_booking_db
 
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  cloud:
    config:
      enabled: false

eureka:
       client:
         service-url:
           defaultZone: http://localhost:8761/eureka
       instance:
        prefer-ip-address: true 

management:
  health:
    circuitbreakers:  
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
     health:
       show-details:  always